			[[++social_facebook:notempty=`<a href="[[++social_facebook]]" target="_blank"><i class="fab fa-facebook-f"></i></a>`]]
			[[++social_twitter:notempty=`<a href="[[++social_twitter]]" target="_blank"><i class="fab fa-twitter"></i></a>`]]
			[[++social_instagram:notempty=`<a href="[[++social_instagram]]" target="_blank"><i class="fab fa-instagram"></i></a>`]]
			[[++social_linkedin:notempty=`<a href="[[++social_linkedin]]" target="_blank"><i class="fab fa-linkedin-in"></i></a>`]]
			[[++social_google:notempty=`<a href="[[++social_google]]" target="_blank"><i class="fab fa-google-plus"></i></a>`]]