<div class="checkboxList" data-control="countries">
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="ALBANIA:G:44" data-search-filter-field="ALBANIA:G:44" style="display: list-item;">
        <input data-filter-field="countries" data-filter-label="Albania" data-filter-value="ALBANIA:G:44" data-filter-type="" type="checkbox" null="" name="ALBANIA:G:44" [[!+c_ALBANIA]]>
        <span>Albania</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="AUSTRIA:G:30" data-search-filter-field="AUSTRIA:G:30" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Austria" data-filter-value="AUSTRIA:G:30" data-filter-type="" type="checkbox" null="" name="AUSTRIA:G:30" [[!+c_AUSTRIA]]> <span>Austria</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="BELGIUM:G:8" data-search-filter-field="BELGIUM:G:8" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Belgium" data-filter-value="BELGIUM:G:8" data-filter-type="" type="checkbox" null="" name="BELGIUM:G:8" [[!+c_BELGIUM]]> <span>Belgium</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="BULGARIA:G:17" data-search-filter-field="BULGARIA:G:17" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Bulgaria" data-filter-value="BULGARIA:G:17" data-filter-type="" type="checkbox" null="" name="BULGARIA:G:17" [[!+c_BULGARIA]]> <span>Bulgaria</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="CROATIA:G:37" data-search-filter-field="CROATIA:G:37" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Croatia" data-filter-value="CROATIA:G:37" data-filter-type="" type="checkbox" null="" name="CROATIA:G:37" [[!+c_CROATIA]]> <span>Croatia</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="CZECH_REPUBLIC:G:18" data-search-filter-field="CZECH_REPUBLIC:G:18" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Czech Republic" data-filter-value="CZECH_REPUBLIC:G:18" data-filter-type="" type="checkbox" null="" name="CZECH_REPUBLIC:G:18" [[!+c_CZECH_REPUBLIC]]> <span>Czech Republic</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="DENMARK:G:29" data-search-filter-field="DENMARK:G:29" style="display: list-item;">
        <input data-filter-field="countries" data-filter-label="Denmark" data-filter-value="DENMARK:G:29" data-filter-type="" type="checkbox" null="" name="DENMARK:G:29" [[!+c_DENMARK]]>
        <span>Denmark</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="ESTONIA:G:19" data-search-filter-field="ESTONIA:G:19" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Estonia" data-filter-value="ESTONIA:G:19" data-filter-type="" type="checkbox" null="" name="ESTONIA:G:19" [[!+c_ESTONIA]]> <span>Estonia</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="FINLAND:G:14" data-search-filter-field="FINLAND:G:14" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Finland" data-filter-value="FINLAND:G:14" data-filter-type="" type="checkbox" null="" name="FINLAND:G:14" [[!+c_FINLAND]]> <span>Finland</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="FRANCE:G:2" data-search-filter-field="FRANCE:G:2" style="display: list-item;"><input data-filter-field="countries" data-filter-label="France" data-filter-value="FRANCE:G:2" data-filter-type="" type="checkbox" null="" name="FRANCE:G:2" [[!+c_FRANCE]]>
        <span>France</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="GEORGIA:G:41" data-search-filter-field="GEORGIA:G:41" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Georgia" data-filter-value="GEORGIA:G:41" data-filter-type="" type="checkbox" null="" name="GEORGIA:G:41" [[!+c_GEORGIA]]> <span>Georgia</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="GERMANY:G:3" data-search-filter-field="GERMANY:G:3" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Germany" data-filter-value="GERMANY:G:3" data-filter-type="" type="checkbox" null="" name="GERMANY:G:3" [[!+c_GERMANY]]> <span>Germany</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="GREECE:G:4" data-search-filter-field="GREECE:G:4" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Greece" data-filter-value="GREECE:G:4" data-filter-type="" type="checkbox" null="" name="GREECE:G:4" [[!+c_GREECE]]>
        <span>Greece</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="HUNGARY:G:22" data-search-filter-field="HUNGARY:G:22" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Hungary" data-filter-value="HUNGARY:G:22" data-filter-type="" type="checkbox" null="" name="HUNGARY:G:22" [[!+c_HUNGARY]]> <span>Hungary</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="ICELAND:G:25" data-search-filter-field="ICELAND:G:25" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Iceland" data-filter-value="ICELAND:G:25" data-filter-type="" type="checkbox" null="" name="ICELAND:G:25" [[!+c_ICELAND]]> <span>Iceland</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="IRELAND:G:10" data-search-filter-field="IRELAND:G:10" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Ireland" data-filter-value="IRELAND:G:10" data-filter-type="" type="checkbox" null="" name="IRELAND:G:10" [[!+c_IRELAND]]> <span>Ireland</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="ISLE_OF_MAN:G:43" data-search-filter-field="ISLE_OF_MAN:G:43" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Isle of Man" data-filter-value="ISLE_OF_MAN:G:43" data-filter-type="" type="checkbox" null="" name="ISLE_OF_MAN:G:43" [[!+c_ISLE_OF_MAN]]> <span>Isle of Man</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="ISRAEL:G:45" data-search-filter-field="ISRAEL:G:45" style="display: list-item;">
        <input data-filter-field="countries" data-filter-label="Israel" data-filter-value="ISRAEL:G:45" data-filter-type="" type="checkbox" null="" name="ISRAEL:G:45" [[!+c_ISRAEL]]>
        <span>Israel</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="ITALY:G:34" data-search-filter-field="ITALY:G:34" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Italy" data-filter-value="ITALY:G:34" data-filter-type="" type="checkbox" null="" name="ITALY:G:34" [[!+c_ITALY]]> <span>Italy</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="LATVIA:G:11" data-search-filter-field="LATVIA:G:11" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Latvia" data-filter-value="LATVIA:G:11" data-filter-type="" type="checkbox" null="" name="LATVIA:G:11" [[!+c_LATVIA]]> <span>Latvia</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="LITHUANIA:G:35" data-search-filter-field="LITHUANIA:G:35" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Lithuania" data-filter-value="LITHUANIA:G:35" data-filter-type="" type="checkbox" null="" name="LITHUANIA:G:35" [[!+c_LITHUANIA]]> <span>Lithuania</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="LUXEMBOURG:G:26" data-search-filter-field="LUXEMBOURG:G:26" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Luxembourg" data-filter-value="LUXEMBOURG:G:26" data-filter-type="" type="checkbox" null="" name="LUXEMBOURG:G:26" [[!+c_LUXEMBOURG]]> <span>Luxembourg</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="MALTA:G:12" data-search-filter-field="MALTA:G:12" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Malta" data-filter-value="MALTA:G:12" data-filter-type="" type="checkbox" null="" name="MALTA:G:12" [[!+c_MALTA]]> <span>Malta</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="MULTINATIONAL_INSTITUTIONS:G:42" data-search-filter-field="MULTINATIONAL_INSTITUTIONS:G:42" style="display: list-item;">
        <input data-filter-field="countries" data-filter-label="Multinational Institutions" data-filter-value="MULTINATIONAL_INSTITUTIONS:G:42" data-filter-type="" type="checkbox" null="" name="MULTINATIONAL_INSTITUTIONS:G:42" [[!+c_MULTINATIONAL_INSTITUTIONS]]> <span>Multinational Institutions</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="NETHERLANDS:G:7" data-search-filter-field="NETHERLANDS:G:7" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Netherlands" data-filter-value="NETHERLANDS:G:7" data-filter-type="" type="checkbox" null="" name="NETHERLANDS:G:7" [[!+c_NETHERLANDS]]> <span>Netherlands</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="NORWAY:G:33" data-search-filter-field="NORWAY:G:33" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Norway" data-filter-value="NORWAY:G:33" data-filter-type="" type="checkbox" null="" name="NORWAY:G:33" [[!+c_NORWAY]]> <span>Norway</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="POLAND:G:5" data-search-filter-field="POLAND:G:5" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Poland" data-filter-value="POLAND:G:5" data-filter-type="" type="checkbox" null="" name="POLAND:G:5" [[!+c_POLAND]]>
        <span>Poland</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="PORTUGAL:G:13" data-search-filter-field="PORTUGAL:G:13" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Portugal" data-filter-value="PORTUGAL:G:13" data-filter-type="" type="checkbox" null="" name="PORTUGAL:G:13" [[!+c_PORTUGAL]]> <span>Portugal</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="ROMANIA:G:36" data-search-filter-field="ROMANIA:G:36" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Romania" data-filter-value="ROMANIA:G:36" data-filter-type="" type="checkbox" null="" name="ROMANIA:G:36" [[!+c_ROMANIA]]> <span>Romania</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="SERBIA:G:39" data-search-filter-field="SERBIA:G:39" style="display: list-item;">
        <input data-filter-field="countries" data-filter-label="Serbia" data-filter-value="SERBIA:G:39" data-filter-type="" type="checkbox" null="" name="SERBIA:G:39" [[!+c_SERBIA]]>
        <span>Serbia</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="SLOVAKIA:G:32" data-search-filter-field="SLOVAKIA:G:32" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Slovakia" data-filter-value="SLOVAKIA:G:32" data-filter-type="" type="checkbox" null="" name="SLOVAKIA:G:32" [[!+c_SLOVAKIA]]> <span>Slovakia</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="SLOVENIA:G:9" data-search-filter-field="SLOVENIA:G:9" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Slovenia" data-filter-value="SLOVENIA:G:9" data-filter-type="" type="checkbox" null="" name="SLOVENIA:G:9" [[!+c_SLOVENIA]]> <span>Slovenia</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="SPAIN:G:1" data-search-filter-field="SPAIN:G:1" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Spain" data-filter-value="SPAIN:G:1" data-filter-type="" type="checkbox" null="" name="SPAIN:G:1" [[!+c_SPAIN]]>
        <span>Spain</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="SWEDEN:G:6" data-search-filter-field="SWEDEN:G:6" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Sweden" data-filter-value="SWEDEN:G:6" data-filter-type="" type="checkbox" null="" name="SWEDEN:G:6" [[!+c_SWEDEN]]>
        <span>Sweden</span>
    </li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="SWITZERLAND:G:28" data-search-filter-field="SWITZERLAND:G:28" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Switzerland" data-filter-value="SWITZERLAND:G:28" data-filter-type="" type="checkbox" null="" name="SWITZERLAND:G:28" [[!+c_SWITZERLAND]]> <span>Switzerland</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="TURKEY:G:49" data-search-filter-field="TURKEY:G:49" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Turkey" data-filter-value="TURKEY:G:49" data-filter-type="" type="checkbox" null="" name="TURKEY:G:49" [[!+c_TURKEY]]> <span>Turkey</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="UKRAINE:G:46" data-search-filter-field="UKRAINE:G:46" style="display: list-item;"><input data-filter-field="countries" data-filter-label="Ukraine" data-filter-value="UKRAINE:G:46" data-filter-type="" type="checkbox" null="" name="UKRAINE:G:46" [[!+c_UKRAINE]]> <span>Ukraine</span></li>
    <li class="checkbox" data-facet-item-set="countries" data-facet-item="UNITED_KINGDOM:G:27" data-search-filter-field="UNITED_KINGDOM:G:27" style="display: list-item;"><input data-filter-field="countries" data-filter-label="United Kingdom" data-filter-value="UNITED_KINGDOM:G:27" data-filter-type="" type="checkbox" null="" name="UNITED_KINGDOM:G:27" [[!+c_UNITED_KINGDOM]]> <span>United Kingdom</span>
    </li>
</div>