<?php
$_lang['asi.form_rating_success_msg'] = 'Thank you, your rating has been sent';
$_lang['asi.form_rating_success_msg_full'] = '<h2>Thank you! We have received your rating</h2><p>Your rating was successfully submitted and has been forwarded to the institution holding these materials. The colleagues will be in touch if any further action is required.</p><p>If you would like to stay up to date with Archives Portal Europe, please <a href="https://docs.google.com/forms/d/e/1FAIpQLSdIvngHSCDhoAAvk8xF_Fun-ENA4z-ID8Pp8XiRu4pbvaPaDA/viewform">join our monthly newsletter</a>.</p>';
$_lang['asi.form_rating_success_msg_full_explore'] = '<h2>Thank you! We have received your rating</h2><p>Your rating was successfully submitted and has been forwarded to the appropriate contact person. They will be in touch if any further action is required.</p><p>If you would like to stay up to date with Archives Portal Europe, please <a href="https://docs.google.com/forms/d/e/1FAIpQLSdIvngHSCDhoAAvk8xF_Fun-ENA4z-ID8Pp8XiRu4pbvaPaDA/viewform">join our monthly newsletter</a>.</p>';
$_lang['asi.form_contact_institution_success_msg_full'] = '<h2>Thank you! We have received your message</h2><p>Your message was successfully submitted and has been forwarded to the institution holding these materials. The colleagues will be in touch as soon as possible, usually in between 10 and 15 working days.</p><p>This is a process independent from Archives Portal Europe. If you have not heard anything from the institution within this time frame, please do send us an email to <a href="mailto:info@archivesportaleurope.net">info@archivesportaleurope.net</a> and we will try to help you with your query.</p><p>If you would like to stay up to date with Archives Portal Europe, please <a href="https://docs.google.com/forms/d/e/1FAIpQLSdIvngHSCDhoAAvk8xF_Fun-ENA4z-ID8Pp8XiRu4pbvaPaDA/viewform">join our monthly newsletter</a>.</p>';
$_lang['asi.form_contact_institution_success_msg_full_explore'] = '<h2>Thank you! We have received your message</h2><p>Your message was successfully submitted and has been forwarded to the appropriate contact person. They will be in touch as soon as possible, usually in between 10 and 15 working days.</p><p>If you have not heard anything back within this time frame, please do send us an email to <a href="mailto:info@archivesportaleurope.net">info@archivesportaleurope.net</a>.</p><p>If you would like to stay up to date with Archives Portal Europe, please <a href="https://docs.google.com/forms/d/e/1FAIpQLSdIvngHSCDhoAAvk8xF_Fun-ENA4z-ID8Pp8XiRu4pbvaPaDA/viewform">join our monthly newsletter</a>.</p>';
$_lang['asi.form_suggestion_success_msg_full'] = '<h2>Thank you! We have received your suggestion</h2><p>Your suggestion was successfully submitted and we will be in touch if we have any further questions.</p><p>If you would like to stay up to date with Archives Portal Europe, please <a href="https://docs.google.com/forms/d/e/1FAIpQLSdIvngHSCDhoAAvk8xF_Fun-ENA4z-ID8Pp8XiRu4pbvaPaDA/viewform">join our monthly newsletter</a>.</p>';
$_lang['asi.form_validation_error'] = 'A form validation error occurred. Please check the values you have entered.';
$_lang['asi.form_required_fields_empty_err_msg'] = 'Not all required fields have been filled in.';
$_lang['asi.form_full_name_required_err_msg'] = 'Your full name is required';
$_lang['asi.form_email_address_required_err_msg'] = 'Your email address is required';
$_lang['asi.form_message_required_err_msg'] = 'A message is required';
$_lang['asi.form_topic_choose_err_msg'] = 'A topic is required';
$_lang['asi.form_title_personal_details'] = 'Personal details';
$_lang['asi.form_successfully_updated_success_msg'] = 'Successfully updated';
$_lang['asi.form_search_no_results_found_err_msg'] = 'No results found for the search term';
$_lang['asi.msg_subscribe_success_msg'] = 'The email address <strong data-populate="blog_subscribe_email"></strong> has been successfully subscribed.';
$_lang['asi.form_a_suggestion_is_required_err_msg'] = 'A suggestion is required';
$_lang['asi.form_upload_file_err_msg'] = 'Incorrect file type or file size too large!';
$_lang['asi.input_new_pwd_err_msg'] = 'A new password is required';
$_lang['asi.input_pwd_not_match_err_msg'] = 'Passwords do not match';
$_lang['asi.input_pwd_must_confirm_err_msg'] = 'You must confirm your new password';
$_lang['asi.input_pwd_not_meet_req_err_msg'] = 'Password does not match requirements';
$_lang['asi.input_choose_preferred_lang'] = 'Please choose a preferred language';
$_lang['asi.err_msg_enter_valid_email'] = 'Please enter a valid email';
$_lang['asi.err_msg_there_are_no_digital_objects'] = 'There are no digital objects';
