<?php
$_lang['asi.form_rating_success_msg'] = 'Thank you, your rating has been sent';
$_lang['asi.form_validation_error'] = 'A form validation error occurred. Please check the values you have entered.';
$_lang['asi.form_required_fields_empty_err_msg'] = 'Not all required fields have been filled in.';
$_lang['asi.form_full_name_required_err_msg'] = 'Your full name is required';
$_lang['asi.form_email_address_required_err_msg'] = 'Your email address is required';
$_lang['asi.form_message_required_err_msg'] = 'A message is required';
$_lang['asi.form_topic_choose_err_msg'] = 'A topic is required';
$_lang['asi.form_title_personal_details'] = 'Personal details';
$_lang['asi.form_successfully_updated_success_msg'] = 'Successfully updated';
$_lang['asi.form_search_no_results_found_err_msg'] = 'No results found for the search term';
$_lang['asi.msg_subscribe_success_msg'] = 'The email address <strong data-populate="blog_subscribe_email"></strong> has been successfully subscribed.';
$_lang['asi.form_a_suggestion_is_required_err_msg'] = 'A suggestion is required';
$_lang['asi.form_upload_file_err_msg'] = 'Incorrect file type or file size too large!';
$_lang['asi.input_new_pwd_err_msg'] = 'A new password is required';
$_lang['asi.input_pwd_not_match_err_msg'] = 'Passwords do not match';
$_lang['asi.input_pwd_must_confirm_err_msg'] = 'You must confirm your new password';
$_lang['asi.input_pwd_not_meet_req_err_msg'] = 'Password does not match requirements';
$_lang['asi.input_choose_preferred_lang'] = 'Please choose a preferred language';
$_lang['asi.err_msg_enter_valid_email'] = 'Please enter a valid email';
$_lang['asi.err_msg_there_are_no_digital_objects'] = 'There are no digital objects';
